server:
   port: 5050
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: Password12
      
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update