server:
   port: 4040
spring:
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp 
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: Password12
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
